server:
  port: 8080

spring:
  application:
    name: chery-demo-service  # 服务名必须写，Nacos 靠它识别

  # Nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

      # Nacos 配置中心
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        file-extension: yaml  # 配置文件格式
        prefix: ${spring.application.name}

  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 自动建表更新，生产用none
    show-sql: true      # 打印SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

# 日志
logging:
  level:
    root: info
    com.chery.cloud: debug